### ISSUE TITLE
unique history for element?

### ISSUE THREAD

**Issue by johanneswilm** [rniwa/undomanager#1]
One thing that is not quite clear from the explanation at the beginning is whether it is the UA or the JavaScript program that decides whether a DOM element has a separate history from the rest of the page. if it is the User Agent, I am afraid it will clash with the usecase of JavaScript editors as all the editors we found history create a unique history for their editor and the "global undo stack" is ignored also for that reason. Also Apple's iCloud Pages has implemented an undo stack for the main editor that is separate from other input/text fields on the same page. We researched that here [1].

[1] https://github.com/w3c/editing/issues/150

**Comment by rniwa** [comment]
Let’s not use this repo for any discussion
